In [6]:
import pandas as pd

In [7]:
import requests

url = "https://streaming-availability.p.rapidapi.com/countries"

querystring = {"output_language":"en"}

headers = {
	"x-rapidapi-key": "3ef653fe0bmsh75ee53ffae7dd44p12b9d0jsn631205a8b255",
	"x-rapidapi-host": "streaming-availability.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'it': {'countryCode': 'it', 'name': 'Italy', 'services': [{'id': 'netflix', 'name': 'Netflix', 'homePage': 'https://www.netflix.com/', 'themeColorCode': '#E50914', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/netflix/logo-light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/netflix/logo-dark-theme.svg', 'whiteImage': 'https://media.movieofthenight.com/services/netflix/logo-white.svg'}, 'streamingOptionTypes': {'addon': False, 'buy': False, 'rent': False, 'free': False, 'subscription': True}, 'addons': []}, {'id': 'prime', 'name': 'Prime Video', 'homePage': 'https://www.primevideo.com/', 'themeColorCode': '#00A8E1', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/logo-dark-theme.svg', 'whiteImage': 'https://media.movieofthenight.com/services/prime/logo-white.svg'}, 'streamingOptionTypes': {'addon': True, 'buy': True, 'rent': True, 'free': True, 'subscription': True}, 'addons': [{'id': 'academiatvit', 'name': 'Acadèmia.tv', 'homePage': 'https://www.primevideo.com/storefront/subscription/academiatvit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/academiatvit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/academiatvit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/academiatvit/white.svg'}}, {'id': 'actionzoneit', 'name': 'Action Zone', 'homePage': 'https://www.primevideo.com/storefront/subscription/actionzoneit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/actionzoneit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/actionzoneit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/actionzoneit/white.svg'}}, {'id': 'yamatoit', 'name': 'Anime Generation', 'homePage': 'https://www.primevideo.com/storefront/subscription/yamatoit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/yamatoit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/yamatoit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/yamatoit/white.svg'}}, {'id': 'anniduemilait', 'name': 'Anni Duemila the movies', 'homePage': 'https://www.primevideo.com/storefront/subscription/anniduemilait', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/anniduemilait/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/anniduemilait/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/anniduemilait/white.svg'}}, {'id': 'appletvit', 'name': 'Apple TV', 'homePage': 'https://www.primevideo.com/storefront/subscription/appletvit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/appletvit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/appletvit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/appletvit/white.svg'}}, {'id': 'blueswanit', 'name': 'Blue Swan Entertainment +', 'homePage': 'https://www.primevideo.com/storefront/subscription/blueswanit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/blueswanit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/blueswanit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/blueswanit/white.svg'}}, {'id': 'buddyfitit', 'name': 'Buddyfit Collection', 'homePage': 'https://www.primevideo.com/storefront/subscription/buddyfitit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/buddyfitit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/buddyfitit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/buddyfitit/white.svg'}}, {'id': 'cgclassicit', 'name': 'CG Classic', 'homePage': 'https://www.primevideo.com/storefront/subscription/cgclassicit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cgclassicit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cgclassicit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cgclassicit/white.svg'}}, {'id': 'cgentit', 'name': 'CG Collection', 'homePage': 'https://www.primevideo.com/storefront/subscription/cgentit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cgentit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cgentit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cgentit/white.svg'}}, {'id': 'cacciatvit', 'name': 'Caccia TV', 'homePage': 'https://www.primevideo.com/storefront/subscription/cacciatvit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cacciatvit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cacciatvit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cacciatvit/white.svg'}}, {'id': 'cartoonclubit', 'name': 'Cartoon Club', 'homePage': 'https://www.primevideo.com/storefront/subscription/cartoonclubit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cartoonclubit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cartoonclubit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cartoonclubit/white.svg'}}, {'id': 'cineautoreit', 'name': 'CineAutore', 'homePage': 'https://www.primevideo.com/storefront/subscription/cineautoreit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cineautoreit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cineautoreit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cineautoreit/white.svg'}}, {'id': 'cineavventurait', 'name': 'CineAvventura', 'homePage': 'https://www.primevideo.com/storefront/subscription/cineavventurait', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cineavventurait/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cineavventurait/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cineavventurait/white.svg'}}, {'id': 'cinebmovieit', 'name': 'CineBmovie', 'homePage': 'https://www.primevideo.com/storefront/subscription/cinebmovieit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinebmovieit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinebmovieit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinebmovieit/white.svg'}}, {'id': 'cinecomicoit', 'name': 'CineComico', 'homePage': 'https://www.primevideo.com/storefront/subscription/cinecomicoit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinecomicoit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinecomicoit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinecomicoit/white.svg'}}, {'id': 'cinedarkit', 'name': 'CineDark', 'homePage': 'https://www.primevideo.com/storefront/subscription/cinedarkit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinedarkit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinedarkit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinedarkit/white.svg'}}, {'id': 'cinemadameplusit', 'name': 'CineMadame Plus', 'homePage': 'https://www.primevideo.com/storefront/subscription/cinemadameplusit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinemadameplusit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinemadameplusit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/cinemadameplusit/white.svg'}}, {'id': 'crunchyrollit', 'name': 'Crunchyroll', 'homePage': 'https://www.primevideo.com/storefront/subscription/crunchyrollit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/crunchyrollit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/crunchyrollit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/crunchyrollit/white.svg'}}, {'id': 'leoneit', 'name': 'C’era una volta…', 'homePage': 'https://www.primevideo.com/storefront/subscription/leoneit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/leoneit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/leoneit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/leoneit/white.svg'}}, {'id': 'danimeit', 'name': 'D-ANIME', 'homePage': 'https://www.primevideo.com/storefront/subscription/danimeit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/danimeit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/danimeit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/danimeit/white.svg'}}, {'id': 'daznstartit', 'name': 'DAZN', 'homePage': 'https://www.primevideo.com/storefront/subscription/daznstartit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/daznstartit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/daznstartit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/daznstartit/white.svg'}}, {'id': 'djazzit', 'name': 'DJAZZ', 'homePage': 'https://www.primevideo.com/storefront/subscription/djazzit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/djazzit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/djazzit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/djazzit/white.svg'}}, {'id': 'djangowesternit', 'name': 'Django Western', 'homePage': 'https://www.primevideo.com/storefront/subscription/djangowesternit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/djangowesternit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/djangowesternit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/djangowesternit/white.svg'}}, {'id': 'tvloveit', 'name': 'Dreamers and Love', 'homePage': 'https://www.primevideo.com/storefront/subscription/tvloveit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/tvloveit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/tvloveit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/tvloveit/white.svg'}}, {'id': 'eaglemagicit', 'name': 'Eagle Magic', 'homePage': 'https://www.primevideo.com/storefront/subscription/eaglemagicit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/eaglemagicit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/eaglemagicit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/eaglemagicit/white.svg'}}, {'id': 'eaglepicturesit', 'name': 'Eagle No Limits', 'homePage': 'https://www.primevideo.com/storefront/subscription/eaglepicturesit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/eaglepicturesit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/eaglepicturesit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/eaglepicturesit/white.svg'}}, {'id': 'fareastit', 'name': 'Far East Channel', 'homePage': 'https://www.primevideo.com/storefront/subscription/fareastit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/fareastit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/fareastit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/fareastit/white.svg'}}, {'id': 'focusselectionit', 'name': 'Focus Selection', 'homePage': 'https://www.primevideo.com/storefront/subscription/focusselectionit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/focusselectionit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/focusselectionit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/focusselectionit/white.svg'}}, {'id': 'duelit', 'name': 'Full Action', 'homePage': 'https://www.primevideo.com/storefront/subscription/duelit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/duelit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/duelit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/duelit/white.svg'}}, {'id': 'maxit', 'name': 'HBO Max', 'homePage': 'https://www.primevideo.com/storefront/subscription/maxit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/maxit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/maxit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/maxit/white.svg'}}, {'id': 'maxsportsit', 'name': 'HBO Max + HBO Max Sport', 'homePage': 'https://www.primevideo.com/storefront/subscription/maxsportsit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/maxsportsit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/maxsportsit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/maxsportsit/white.svg'}}, {'id': 'hayuit', 'name': 'Hayu', 'homePage': 'https://www.primevideo.com/storefront/subscription/hayuit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/hayuit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/hayuit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/hayuit/white.svg'}}, {'id': 'historyplayit', 'name': 'History Play', 'homePage': 'https://www.primevideo.com/storefront/subscription/historyplayit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/historyplayit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/historyplayit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/historyplayit/white.svg'}}, {'id': 'intertvit', 'name': 'INTERTV', 'homePage': 'https://www.primevideo.com/storefront/subscription/intertvit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/intertvit/light-theme.svg', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/intertvit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/intertvit/white.svg'}}, {'id': 'iwonderfullit', 'name': 'IWONDERFULL', 'homePage': 'https://www.primevideo.com/storefront/subscription/iwonderfullit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/iwonderfullit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/iwonderfullit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/iwonderfullit/white.svg'}}, {'id': 'infinityit', 'name': 'Infinity Selection', 'homePage': 'https://www.primevideo.com/storefront/subscription/infinityit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/infinityit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/infinityit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/infinityit/white.svg'}}, {'id': 'juventustvit', 'name': 'Juventus TV', 'homePage': 'https://www.primevideo.com/storefront/subscription/juventustvit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/juventustvit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/juventustvit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/juventustvit/white.svg'}}, {'id': 'lafit', 'name': 'LaF – Feltrinelli Media Collection', 'homePage': 'https://www.primevideo.com/storefront/subscription/lafit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/lafit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/lafit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/lafit/white.svg'}}, {'id': 'levitedeglialtriit', 'name': 'Le vite degli altri', 'homePage': 'https://www.primevideo.com/storefront/subscription/levitedeglialtriit', 'themeColorCode': '#000000', 'imageSet': {'lightThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/levitedeglialtriit/light-theme.png', 'darkThemeImage': 'https://media.movieofthenight.com/services/prime/it/addons/levitedeglialtriit/dark-theme.png', 'whiteImage': 'https://media.movieofthenight.com/services/prime/it/addons/levitedeglialtriit/white.svg'}}, {'id': 'leonefilmmaxit', 'name': 'Leone Film MAX', 'homePage': 'https://www.primevideo.com/storefront/subscription/leonefilmm

In [16]:
data = response.json()

In [23]:
countries = pd.DataFrame(data.values())
countries.head()

  countryCode         name                                           services
0          it        Italy  [{'id': 'netflix', 'name': 'Netflix', 'homePag...
1          sg    Singapore  [{'id': 'netflix', 'name': 'Netflix', 'homePag...
2          gr       Greece  [{'id': 'netflix', 'name': 'Netflix', 'homePag...
3          ie      Ireland  [{'id': 'netflix', 'name': 'Netflix', 'homePag...
4          nl  Netherlands  [{'id': 'netflix', 'name': 'Netflix', 'homePag...

In [30]:
country_list = []

for country in data.values():
    country_info = {
        'countryCode': country['countryCode'],
        'name': country['name']
    }

    country_list.append(country_info)

countries = pd.DataFrame(country_list)
countries.sample(5)

   countryCode        name
3           ie     Ireland
62          id   Indonesia
61          hr     Croatia
26          az  Azerbaijan
9           pt    Portugal

In [32]:
countries.shape

(65, 2)

In [33]:
countries.info()

<class 'pandas.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   countryCode  65 non-null     str
 1   name         65 non-null     str
dtypes: str(2)
memory usage: 1.8 KB

In [34]:
countries['name'].unique()

<ArrowStringArray>
[          'Italy',       'Singapore',          'Greece',         'Ireland',
     'Netherlands',     'New Zealand',          'Sweden',  'United Kingdom',
          'Turkey',        'Portugal',        'Malaysia',        'Thailand',
     'Switzerland',          'France',     'Philippines',    'South Africa',
         'Vietnam',         'Denmark',         'Austria', 'North Macedonia',
      'Costa Rica',       'Venezuela',          'Panama',         'Germany',
         'Ukraine',          'Canada',      'Azerbaijan',         'Moldova',
  'Czech Republic',           'Spain',       'Australia',          'Poland',
         'Ecuador',         'Bolivia',        'Bulgaria',       'Argentina',
          'Brazil',           'Japan',           'Chile',         'Belgium',
         'Finland',        'Slovakia',         'Romania',   'United States',
     'South Korea',     'El Salvador',         'Iceland',          'Serbia',
          'Mexico',        'Colombia',        'Slovenia',         'Hungary',
           'India',       'Guatemala',          'Cyprus',          'Israel',
            'Peru',        'Honduras',       'Lithuania', 'United Emirates',
         'Estonia',         'Croatia',       'Indonesia',          'Norway',
       'Hong Kong']
Length: 65, dtype: str

In [35]:
countries.isnull().sum()

countryCode    0
name           0
dtype: int64