In [4]:
import pandas as pd

# WORKING WITH JSON

In [2]:
pd.read_json('pokedex.json')

,id,name,type,base
0,1,"{'english': 'Bulbasaur', 'japanese': 'フシギダネ', ...","[Grass, Poison]","{'HP': 45, 'Attack': 49, 'Defense': 49, 'Sp. A..."
1,2,"{'english': 'Ivysaur', 'japanese': 'フシギソウ', 'c...","[Grass, Poison]","{'HP': 60, 'Attack': 62, 'Defense': 63, 'Sp. A..."
2,3,"{'english': 'Venusaur', 'japanese': 'フシギバナ', '...","[Grass, Poison]","{'HP': 80, 'Attack': 82, 'Defense': 83, 'Sp. A..."
3,4,"{'english': 'Charmander', 'japanese': 'ヒトカゲ', ...",[Fire],"{'HP': 39, 'Attack': 52, 'Defense': 43, 'Sp. A..."
4,5,"{'english': 'Charmeleon', 'japanese': 'リザード', ...",[Fire],"{'HP': 58, 'Attack': 64, 'Defense': 58, 'Sp. A..."
...,...,...,...,...
804,805,"{'english': 'Stakataka', 'japanese': 'ツンデツンデ',...","[Rock, Steel]","{'HP': 61, 'Attack': 131, 'Defense': 211, 'Sp...."
805,806,"{'english': 'Blacephalon', 'japanese': 'ズガドーン'...","[Fire, Ghost]","{'HP': 53, 'Attack': 127, 'Defense': 53, 'Sp. ..."
806,807,"{'english': 'Zeraora', 'japanese': 'ゼラオラ', 'ch...",[Electric],"{'HP': 88, 'Attack': 112, 'Defense': 75, 'Sp. ..."
807,808,"{'english': 'Meltan', 'japanese': 'メルタン', 'chi...",[Steel],"{'HP': 46, 'Attack': 65, 'Defense': 65, 'Sp. A..."
808,809,"{'english': 'Melmetal', 'japanese': 'メルメタル', '...",[Steel],"{'HP': 135, 'Attack': 143, 'Defense': 143, 'Sp..."

In [6]:
#to read json data directly from a url
#pd.read_csv('url')

# WORKING WITH SQL

In [8]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in C:\Users\safiy\anaconda3\Lib\site-packages (2.2.9)

In [9]:
import mysql.connector

In [11]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [12]:
pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\safiy\AppData\Local\Temp\ipykernel_13168\374620591.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [16]:
    pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'",conn)

C:\Users\safiy\AppData\Local\Temp\ipykernel_13168\1269101506.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'",conn)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]

In [18]:
pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 50",conn)

C:\Users\safiy\AppData\Local\Temp\ipykernel_13168\4050581254.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 50",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34,AL
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
4,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537,VU
190,WSM,Samoa,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169,WS
191,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780,YE
192,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792,YU
193,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716,ZA

In [20]:
pd.read_sql_query("SELECT * FROM countrylanguage  WHERE language LIKE 'English' ",conn)

C:\Users\safiy\AppData\Local\Temp\ipykernel_13168\3454700425.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM countrylanguage  WHERE language LIKE 'English' ",conn)

   CountryCode Language IsOfficial  Percentage
0          ABW  English          F         9.5
1          AIA  English          T         0.0
2          ANT  English          F         7.8
3          ASM  English          T         3.1
4          ATG  English          T         0.0
5          AUS  English          T        81.2
6          BHR  English          F         0.0
7          BLZ  English          T        50.8
8          BMU  English          T       100.0
9          BRB  English          T         0.0
10         BRN  English          F         3.1
11         CAN  English          T        60.4
12         CCK  English          T         0.0
13         COK  English          F         0.0
14         CXR  English          T         0.0
15         CYM  English          T         0.0
16         DNK  English          F         0.3
17         FLK  English          T         0.0
18         GBR  English          T        97.3
19         GIB  English          T        88.9
20         GUM  English          T        37.5
21         HKG  English          T         2.2
22         IRL  English          T        98.4
23         ISL  English          F         0.0
24         JPN  English          F         0.1
25         KNA  English          T         0.0
26         KWT  English          F         0.0
27         LCA  English          T        20.0
28         LSO  English          T         0.0
29         MAC  English          F         0.5
30         MCO  English          F         6.5
31         MDV  English          F         0.0
32         MHL  English          T         0.0
33         MLT  English          T         2.1
34         MNP  English          T         4.8
35         MSR  English          T         0.0
36         MYS  English          F         1.6
37         NFK  English          T         0.0
38         NIU  English          T         0.0
39         NOR  English          F         0.5
40         NRU  English          T         7.5
41         NZL  English          T        87.0
42         PLW  English          T         3.2
43         PRI  English          F        47.4
44         SHN  English          T         0.0
45         SYC  English          T         3.8
46         TCA  English          T         0.0
47         TKL  English          T         0.0
48         TON  English          T         0.0
49         TTO  English          F        93.5
50         TUV  English          T         0.0
51         UMI  English          T         0.0
52         USA  English          T        86.2
53         VCT  English          T         0.0
54         VGB  English          T         0.0
55         VIR  English          T        81.7
56         VUT  English          T        28.3
57         WSM  English          T         0.6
58         ZAF  English          T         8.5
59         ZWE  English          T         2.2